import { useEffect, useState } from 'react'
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import * as Linking from 'expo-linking'
import { isSupabaseConfigured, supabase } from '@/lib/supabase'
import { Restaurant, Room } from '@/lib/types'

const demo: Restaurant[] = [
  { place_id:'demo-1', name:'Nyonya Garden', rating:4.7, ratings:1840, vicinity:'Bukit Bintang' },
  { place_id:'demo-2', name:'Sora Ramen House', rating:4.6, ratings:926, vicinity:'Jalan Sultan Ismail' },
  { place_id:'demo-3', name:'Sambal & Stone', rating:4.5, ratings:611, vicinity:'Kampung Baru' },
]
type Screen = 'home'|'create'|'join'|'swipe'|'result'|'history'
export default function Index() {
  const [user, setUser] = useState<any>(); const [previewUser, setPreviewUser] = useState<any>(); const [screen, setScreen] = useState<Screen>('home'); const [room, setRoom] = useState<Room>()
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>setUser(data.session?.user)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user)); return ()=>data.subscription.unsubscribe() },[])
  const activeUser = user || previewUser
  if (!activeUser) return <SignIn onDemo={()=>setPreviewUser({id:'preview-user',email:'demo@bite.local',user_metadata:{display_name:'Alex'}})}/>
  if (screen==='create') return <Create onBack={()=>setScreen('home')} onDone={(r: Room)=>{setRoom(r);setScreen('swipe')}}/>
  if (screen==='join') return <Join onBack={()=>setScreen('home')} onDone={(r: Room)=>{setRoom(r);setScreen('swipe')}}/>
  if (screen==='swipe'&&room) return <Swipes room={room} user={activeUser} done={()=>setScreen('result')}/>
  if (screen==='result'&&room) return <Result room={room} history={()=>setScreen('history')} home={()=>setScreen('home')}/>
  if (screen==='history') return <History back={()=>setScreen('home')}/>
  return <Page><Text style={s.logo}>bite.</Text><Text style={s.eyebrow}>HEY, {(activeUser.user_metadata.display_name||activeUser.email?.split('@')[0]).toUpperCase()}</Text><Text style={s.title}>What are we{`\n`}craving?</Text><Text style={s.copy}>Create a room for friends or jump into one with a code.</Text><Button text="Start a food room" onPress={()=>setScreen('create')}/><Button text="Join with a code" outline onPress={()=>setScreen('join')}/><Link text="Your food history" onPress={()=>setScreen('history')}/><Link text="Sign out" muted onPress={()=>{setPreviewUser(undefined);supabase.auth.signOut()}}/></Page>
}
function SignIn({onDemo}:any){ const [email,setEmail]=useState(''); const [busy,setBusy]=useState(false); async function go(){if(!/^\S+@\S+\.\S+$/.test(email))return Alert.alert('Enter your email','Use an email address where you can receive a sign-in link.');setBusy(true);const {error}=await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{emailRedirectTo:Linking.createURL('/')}});setBusy(false);if(error)Alert.alert('Could not send link',error.message);else Alert.alert('Check your inbox','We sent a secure sign-in link to your email.') } return <View style={s.auth}><Text style={s.logo}>bite.</Text><Text style={s.title}>Pick dinner{`\n`}together.</Text><Text style={s.copy}>The fair way for your group to find a restaurant everyone wants.</Text>{isSupabaseConfigured?<><Field label="EMAIL ADDRESS" value={email} set={setEmail}/><Button text={busy?'Sending link…':'Email me a sign-in link'} onPress={go}/><Text style={s.fine}>No password to remember. We’ll email you a one-time secure sign-in link.</Text></>:<><Button text="Explore demo" onPress={onDemo}/><Text style={s.fine}>Preview mode uses sample people and restaurants. Add Supabase credentials to enable email sign-in.</Text></>}</View> }
function Create({onBack,onDone}:any){const [area,setArea]=useState('Bukit Bintang, Kuala Lumpur');const [radius,setRadius]=useState('3');const [minutes,setMinutes]=useState('20');const [busy,setBusy]=useState(false);async function go(){if(!isSupabaseConfigured)return onDone({id:'demo-room',code:'B1TE42',area,radius_km:Number(radius),swipe_deadline:new Date(Date.now()+Number(minutes)*60000).toISOString()});setBusy(true);const {data,error}=await supabase.rpc('create_food_room',{p_area:area,p_radius_km:Number(radius),p_deadline:new Date(Date.now()+Number(minutes)*60000).toISOString()});setBusy(false);if(error)return Alert.alert('Could not create room',error.message);onDone(data)}return <Page><Back onPress={onBack}/><Text style={s.title}>Set the table.</Text><Text style={s.copy}>Everyone swipes until your timer ends.</Text><Field label="AREA OR NEIGHBOURHOOD" value={area} set={setArea}/><View style={s.row}><View style={s.half}><Field label="RADIUS (KM)" value={radius} set={setRadius}/></View><View style={s.half}><Field label="SWIPE TIME (MIN)" value={minutes} set={setMinutes}/></View></View><Text style={s.fine}>Individual swipes are private; only the group result is shared.</Text><Button text={busy?'Creating…':'Create room'} onPress={go}/></Page>}
function Join({onBack,onDone}:any){const [code,setCode]=useState('');async function go(){if(!isSupabaseConfigured)return onDone({id:'demo-room',code:code.trim().toUpperCase()||'B1TE42',area:'Bukit Bintang, Kuala Lumpur',radius_km:3,swipe_deadline:new Date(Date.now()+1200000).toISOString()});const {data,error}=await supabase.rpc('join_food_room',{p_code:code.trim().toUpperCase()});if(error)return Alert.alert('Could not join',error.message);onDone(data)}return <Page><Back onPress={onBack}/><Text style={s.title}>Join the{`\n`}decision.</Text><Text style={s.copy}>Ask the host for their six-character room code.</Text><Field label="ROOM CODE" value={code} set={setCode}/><Button text="Join room" onPress={go}/></Page>}
function Swipes({room,user,done}:any){const [i,setI]=useState(0);const [places,setPlaces]=useState<Restaurant[]>(isSupabaseConfigured?[]:demo);const [loading,setLoading]=useState(isSupabaseConfigured);useEffect(()=>{if(!isSupabaseConfigured)return;supabase.functions.invoke('places-search',{body:{roomId:room.id}}).then(({data,error})=>{if(error||!data?.results?.length)Alert.alert('Could not find restaurants',error?.message||'Try a more specific area.');else setPlaces(data.results.map((p:any)=>({...p,ratings:p.user_ratings_total||0})));setLoading(false)})},[room.id]);const x=places[i];async function vote(vote:string){if(!x)return;if(!isSupabaseConfigured)return i+1===places.length?done():setI(i+1);const {error}=await supabase.from('room_swipes').upsert({room_id:room.id,user_id:user.id,place_id:x.place_id,place_name:x.name,place_rating:x.rating,vote},{onConflict:'room_id,user_id,place_id'});if(error)return Alert.alert('Swipe not saved',error.message);i+1===places.length?done():setI(i+1)}if(loading)return <Page><Text style={s.title}>Finding nearby{`\n`}restaurants…</Text><Text style={s.copy}>Searching Google Places around {room.area}.</Text></Page>;if(!x)return <Page><Text style={s.title}>No restaurants{`\n`}found.</Text><Text style={s.copy}>Ask the host to try a more specific area or a larger radius.</Text></Page>;return <Page><Text style={s.eyebrow}>ROOM {room.code} · SWIPE NOW</Text><Text style={s.title}>Your next{`\n`}bite?</Text><View style={s.card}><View style={s.photo}><Text style={s.emoji}>🍜</Text></View><Text style={s.restaurant}>{x.name}</Text><Text style={s.address}>{x.vicinity}</Text><Text style={s.rating}>★ {x.rating} <Text style={s.address}>({x.ratings.toLocaleString()} Google ratings)</Text></Text></View><View style={s.votes}><Pressable style={[s.vote,s.no]} onPress={()=>vote('no')}><Text style={s.vt}>✕</Text></Pressable><Pressable style={[s.vote,s.super]} onPress={()=>vote('super')}><Text style={s.vt}>★</Text></Pressable><Pressable style={[s.vote,s.yes]} onPress={()=>vote('yes')}><Text style={s.vt}>♥</Text></Pressable></View><Text style={s.help}>Nope · Super-like · Yes ({i+1}/{places.length})</Text><Link text="Finish swiping" onPress={done}/></Page>}
function Result({room,history,home}:any){const [tie,setTie]=useState(false);const [a,setA]=useState(0);const [b,setB]=useState(0);const won=a===3||b===3;return <Page><Text style={s.eyebrow}>ROOM {room.code}</Text>{tie?<><Text style={s.title}>{won?'We have a winner!':'Tie breaker.'}</Text><Text style={s.copy}>{won?`Team ${a===3?'A':'B'} picks the restaurant.`:'Guess the food emoji. First team to 3 wins.'}</Text><View style={s.game}><Text style={s.gameEmoji}>🧀 + 🍰</Text><Text style={s.word}>_ _ _ _ _ _ _ _ _</Text><Text style={s.address}>What food is this?</Text></View><View style={s.row}><Pressable style={s.team} onPress={()=>setA(Math.min(3,a+1))}><Text style={s.buttonText}>Team A · {a}/3</Text></Pressable><Pressable style={s.team} onPress={()=>setB(Math.min(3,b+1))}><Text style={s.buttonText}>Team B · {b}/3</Text></Pressable></View>{won&&<Button text="Save the choice" onPress={history}/>}</>:<><Text style={s.title}>Dinner is{`\n`}decided.</Text><View style={s.winner}><Text style={s.emoji}>🍜</Text><Text style={s.restaurant}>Nyonya Garden</Text><Text style={s.rating}>★ 4.7 · Group favourite</Text><Text style={s.address}>Bukit Bintang</Text></View><Text style={s.copy}>Keep the room open; after dinner everyone can add a public review.</Text><Button text="View food history" onPress={history}/></>}<Link text={tie?'Back to result':'It’s a tie? Start emoji game'} onPress={()=>setTie(!tie)}/><Link text="Leave room" muted onPress={home}/></Page>}
function History({back}:any){return <Page><Back onPress={back}/><Text style={s.title}>Your food{`\n`}history.</Text><Text style={s.copy}>The more you rate, the smarter your next suggestion becomes.</Text><View style={s.history}><Text style={s.restaurant}>Nyonya Garden</Text><Text style={s.rating}>★ 4.7 · Your food rating 5 · Vibe 4</Text><Text style={s.address}>Visited with Friday Food Club · 2 Sep</Text></View><View style={s.variety}><Text style={s.varietyTitle}>A little variety?</Text><Text style={s.copy}>You’ve had ramen 3 times in two weeks. Your taste buds might enjoy a plot twist.</Text></View></Page>}
function Page({children}:any){return <ScrollView contentContainerStyle={s.page}>{children}</ScrollView>} function Button({text,onPress,outline}:any){return <Pressable onPress={onPress} style={[s.button,outline&&s.outline]}><Text style={[s.buttonText,outline&&s.outlineText]}>{text}</Text></Pressable>}function Link({text,onPress,muted}:any){return <Pressable onPress={onPress}><Text style={[s.link,muted&&s.muted]}>{text}</Text></Pressable>}function Back({onPress}:any){return <Pressable onPress={onPress}><Text style={s.back}>← Back</Text></Pressable>}function Field({label,value,set}:any){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} style={s.input}/></View>}
const s=StyleSheet.create({auth:{flex:1,width:'100%',justifyContent:'center',padding:28,backgroundColor:'#FFF8EF'},page:{flexGrow:1,width:'100%',padding:25,paddingTop:62,backgroundColor:'#FFF8EF'},logo:{fontSize:31,fontWeight:'900',color:'#FF5C35',marginBottom:34},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#E45433',marginBottom:10},title:{fontSize:42,fontWeight:'900',letterSpacing:-2,lineHeight:44,color:'#241F1B',marginBottom:14},copy:{fontSize:16,lineHeight:23,color:'#6B625D',marginBottom:25},button:{backgroundColor:'#FF5C35',padding:17,borderRadius:15,alignItems:'center',marginTop:8},buttonText:{color:'#FFF',fontSize:16,fontWeight:'800'},outline:{backgroundColor:'transparent',borderWidth:1.5,borderColor:'#241F1B',marginTop:12},outlineText:{color:'#241F1B'},link:{textAlign:'center',fontWeight:'800',color:'#E45433',marginTop:25},muted:{color:'#8A817C',marginTop:16},fine:{fontSize:12,lineHeight:18,color:'#8A817C',textAlign:'center',marginVertical:18},back:{color:'#E45433',fontWeight:'800',marginBottom:28},field:{marginBottom:15},label:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#6B625D',marginBottom:7},input:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#DED5CC',borderRadius:13,padding:15,fontSize:16},row:{flexDirection:'row',gap:10},half:{flex:1},card:{backgroundColor:'#FFF',borderRadius:22,padding:18,elevation:3},photo:{height:180,borderRadius:15,backgroundColor:'#FFE2CA',alignItems:'center',justifyContent:'center',marginBottom:17},emoji:{fontSize:70},restaurant:{fontSize:25,fontWeight:'900',color:'#241F1B'},address:{fontSize:14,color:'#817771',marginTop:5},rating:{fontSize:15,color:'#E45433',fontWeight:'800',marginTop:9},votes:{flexDirection:'row',justifyContent:'space-around',marginTop:25},vote:{width:64,height:64,borderRadius:32,justifyContent:'center',alignItems:'center'},vt:{fontSize:29,color:'#FFF',fontWeight:'900'},no:{backgroundColor:'#292421'},super:{backgroundColor:'#F9B43D'},yes:{backgroundColor:'#FF5C35'},help:{textAlign:'center',color:'#817771',marginTop:10},winner:{backgroundColor:'#FFF',borderRadius:22,padding:25,alignItems:'center',marginBottom:20},game:{backgroundColor:'#FFF',borderRadius:22,padding:30,alignItems:'center'},gameEmoji:{fontSize:52},word:{fontWeight:'900',letterSpacing:3,fontSize:20,color:'#241F1B',marginTop:19},team:{backgroundColor:'#292421',padding:15,borderRadius:13,flex:1,alignItems:'center',marginTop:18},history:{backgroundColor:'#FFF',padding:18,borderRadius:17,marginBottom:13},variety:{backgroundColor:'#FFE2CA',padding:19,borderRadius:17},varietyTitle:{fontSize:18,fontWeight:'900',color:'#A23D24',marginBottom:7}})
